# Generated by Django 4.1.1 on 2022-10-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Room_no', models.CharField(max_length=50)),
                ('Time_in', models.DateTimeField(auto_now=True)),
                ('Time_out', models.DateTimeField(auto_now=True)),
                ('Contact', models.CharField(max_length=20)),
            ],
        ),
    ]
