# Generated by Django 4.1.1 on 2022-10-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Time_out',
            field=models.DateTimeField(),
        ),
    ]
