# Generated by Django 4.1.1 on 2022-10-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_alter_details_time_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Time_out',
            new_name='Time_Out',
        ),
    ]
