# Generated by Django 4.1.1 on 2022-10-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_details_adhar_id_alter_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
