# Generated by Django 4.1.1 on 2022-10-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_alter_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Time_Out',
            field=models.DateTimeField(blank=True),
        ),
    ]
