# Generated by Django 4.1.1 on 2022-10-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0011_alter_details_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='id',
            field=models.BigAutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
