# Generated by Django 4.1.1 on 2022-10-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0012_alter_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
