# Generated by Django 4.1.1 on 2022-11-01 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0014_guestdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('room_size', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=50)),
                ('room_price', models.CharField(max_length=50)),
                ('reserved_room', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name_plural': 'Details'},
        ),
        migrations.AlterModelOptions(
            name='guestdetails',
            options={'verbose_name_plural': 'guestDetails'},
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.CharField(max_length=50)),
                ('checkin_datetime', models.DateTimeField(auto_now_add=True)),
                ('checkout_datetime', models.DateTimeField(null=True)),
                ('amount', models.CharField(max_length=50)),
                ('Guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.guestdetails')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.rooms')),
            ],
        ),
    ]
