# Generated by Django 4.1.1 on 2022-11-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0015_rooms_alter_details_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Time_Out',
            field=models.DateTimeField(null=True),
        ),
    ]
